name: in_app_purchase
description: A new Flutter package project.
version: 0.0.1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  #* Local DB
  preferences_utilities:
    path: ../preferences_utilities
  
  utilities:
    path: ../utilities

  #* State managment
  flutter_bloc: ^8.1.5
  provider: ^6.1.2

  #* Permissions
  permission_handler: ^11.3.1

  #? Uitity
  equatable: ^2.0.5
  rxdart: ^0.27.7
  intl: ^0.18.0
  date_time_format: ^2.0.1
  units_converter: ^3.0.0

  #* Network
  dio: ^5.4.2+1
  json_annotation: ^4.8.1
  http: ^1.2.1

  #* Purchases
  purchases_flutter: ^8.2.1

  logger: ^1.4.0

  #* Widgets
  timer_count_down: ^2.2.2
  nested: ^1.0.0

dev_dependencies:
  build_runner: ">=2.1.1"
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  json_serializable: ^6.7.1
  lint: ^2.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
